-- Regnum Aeternum — D1 schema addition: Fiducia Banking System
-- Migration 0006 — Banking System (Phase 1: Schema)
--
-- Apply with:
--   wrangler d1 execute regnum-aeternum-db --local  --file=./migrations/0006_banking.sql
--   wrangler d1 execute regnum-aeternum-db --remote --file=./migrations/0006_banking.sql
--
-- This migration creates the complete schema for the Fiducia Banking System
-- web integration. All account data, transactions, cards, shareholders,
-- company value history, banker assignments, and ComputerCraft terminal
-- tokens live here.
--
-- Account keys use the format 1000XXXXRRRRRRRR (identical to the in-game CC
-- Bank Server) so that existing Fiducia card files (fiducia.txt) remain
-- fully compatible with the HTTP bridge.
-- ============================================================

-- ============================================================
-- banking_settings (singleton — always id = 1)
--
-- Global bank configuration. Mirrors the CC Bank Server's settings.txt
-- but stored atomically in D1. The application layer always reads this
-- single row and updates it in-place; never inserts additional rows.
-- ============================================================
CREATE TABLE IF NOT EXISTS banking_settings (
  id                INTEGER PRIMARY KEY CHECK (id = 1),

  -- JSON object mapping currency type name to web-$ value per base item.
  --   diamond  → 1 diamond    (CC internal value 1, web $ = price * 1)
  --   gold     → 1 gold nugget (CC internal value 1)
  --   emerald  → 1 emerald    (CC internal value 1)
  --   netherite→ 1 ingot      (CC internal value 1)
  -- Example: {"diamond":100,"gold":10,"emerald":50,"netherite":500}
  currency_prices   TEXT    NOT NULL DEFAULT '{"diamond":100,"gold":10,"emerald":50,"netherite":500}',

  -- Every $cumulative_limit transferred to/from an account, the fee fires.
  cumulative_limit  INTEGER NOT NULL DEFAULT 10000,

  -- Amount charged (moved to bank_owner_key) when cumulative_limit is hit.
  cumulative_price  INTEGER NOT NULL DEFAULT 100,

  -- Key of the treasury account that collects fees. Empty = fee disabled.
  bank_owner_key    TEXT    NOT NULL DEFAULT '',

  -- Tax system -------------------------------------------------------
  tax_enabled           INTEGER NOT NULL DEFAULT 0,    -- 0 | 1
  tax_rate_personal     REAL    NOT NULL DEFAULT 0,    -- percent, e.g. 5 = 5 %
  tax_rate_company      REAL    NOT NULL DEFAULT 0,
  tax_threshold         REAL    NOT NULL DEFAULT 0,    -- minimum balance before tax applies
  tax_period_days       INTEGER NOT NULL DEFAULT 7,    -- 7 | 14 | 30
  tax_last_run_at       TEXT    NOT NULL DEFAULT '',   -- ISO timestamp; empty = never run
  -- ------------------------------------------------------------------

  created_at        TEXT    NOT NULL,
  updated_at        TEXT    NOT NULL
);

-- Seed the singleton row. INSERT OR IGNORE so re-running the migration
-- is safe and never overwrites existing configuration.
INSERT OR IGNORE INTO banking_settings (id, created_at, updated_at)
VALUES (1, datetime('now'), datetime('now'));


-- ============================================================
-- banking_accounts
-- Every personal, company, and treasury account in the system.
-- ============================================================
CREATE TABLE IF NOT EXISTS banking_accounts (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,

  -- 1000XXXXRRRRRRRR: 4-digit zero-padded sequential number (XXXX)
  -- followed by 8 random decimal digits (RRRRRRRR).
  -- Example: '1000000147392841'. Generated by the application layer;
  -- preserved verbatim from the CC system for card compatibility.
  key           TEXT    NOT NULL UNIQUE,

  name          TEXT    NOT NULL,
  balance       REAL    NOT NULL DEFAULT 0,

  -- Stored as the CC integer colour constant (e.g. colors.gray = 16384).
  -- The front-end maps CC colour integers to CSS colours.
  color         INTEGER NOT NULL DEFAULT 16384,

  type          TEXT    NOT NULL DEFAULT 'personal'
                CHECK (type IN ('personal', 'company', 'treasury')),

  -- Company accounts: key of the owning personal account. Others: ''.
  owner_key     TEXT    NOT NULL DEFAULT '',

  -- Personal and company accounts: key of their Treasury (organisational
  -- scope). Bankers can only see/act on accounts with their treasury_key.
  -- Treasury accounts themselves: ''.
  treasury_key  TEXT    NOT NULL DEFAULT '',

  -- Online password for Fiduciapp and the web banking portal.
  -- Two formats are accepted (compareAny() in worker/lib/passwords.js):
  --   Web-set:  'pbkdf2:<iters>:<b64salt>:<b64hash>'
  --   CC-set:   '<sha256hex>:<salt>:<iterations>'  (ASHA-512)
  password_hash TEXT    NOT NULL DEFAULT '',

  -- Company accounts: total outstanding shares. Personal/treasury: 0.
  shares        INTEGER NOT NULL DEFAULT 0,

  -- Treasury accounts: 2-4 letter identifier printed on Fiducia cards.
  -- Stored UPPER CASE (e.g. 'RA', 'GOV', 'CROWN'). Others: ''.
  tag           TEXT    NOT NULL DEFAULT '',

  frozen        INTEGER NOT NULL DEFAULT 0,  -- 0 | 1

  -- Running total of money moved since the last cumulative fee deduction.
  -- Decrements by cumulative_limit each time the fee fires.
  cumulative    REAL    NOT NULL DEFAULT 0,

  -- Web user linked to this personal account. NULL = not linked.
  -- Allows the citizen banking portal to show balance on session login
  -- without requiring a physical card.
  user_id       INTEGER REFERENCES users(id) ON DELETE SET NULL,

  created_at    TEXT    NOT NULL,
  updated_at    TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bk_accounts_key      ON banking_accounts(key);
CREATE INDEX IF NOT EXISTS idx_bk_accounts_type     ON banking_accounts(type);
CREATE INDEX IF NOT EXISTS idx_bk_accounts_treasury ON banking_accounts(treasury_key);
CREATE INDEX IF NOT EXISTS idx_bk_accounts_owner    ON banking_accounts(owner_key);
CREATE INDEX IF NOT EXISTS idx_bk_accounts_user     ON banking_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_bk_accounts_frozen   ON banking_accounts(frozen);
CREATE INDEX IF NOT EXISTS idx_bk_accounts_name     ON banking_accounts(name COLLATE NOCASE);


-- ============================================================
-- banking_transactions
-- Immutable ledger of every financial event.
-- One row per operation (unlike the CC log which duplicates per account).
-- The application layer derives each account's perspective on read.
-- ============================================================
CREATE TABLE IF NOT EXISTS banking_transactions (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,

  -- Sender account key.
  -- Special sentinel values (no real account):
  --   '__deposit__'   Physical ATM item deposit (money created from items)
  --   '__system__'    Internal operations (taxes, fee deductions)
  from_key            TEXT    NOT NULL,

  -- Recipient account key.
  -- Special sentinel values:
  --   '__withdraw__'  Physical ATM item withdrawal (money destroyed for items)
  --   '__system__'    Internal operations
  to_key              TEXT    NOT NULL,

  amount              REAL    NOT NULL CHECK (amount > 0),

  -- Balances immediately after this operation; enables log replay and
  -- the "resulting balance" column in the transaction log UI.
  from_balance_after  REAL    NOT NULL,
  to_balance_after    REAL    NOT NULL,

  description         TEXT    NOT NULL DEFAULT '',

  -- Audit trail for who triggered the operation:
  --   'web:<userId>'              Citizen or admin via browser
  --   'cc:<terminalType>:<ccId>'  CC terminal via HTTP bridge
  --   'system:cron'               Scheduled tax cron trigger
  --   'system:fee'                Cumulative fee auto-deduction
  initiated_by        TEXT    NOT NULL DEFAULT 'system',

  created_at          TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bk_tx_from ON banking_transactions(from_key);
CREATE INDEX IF NOT EXISTS idx_bk_tx_to   ON banking_transactions(to_key);
CREATE INDEX IF NOT EXISTS idx_bk_tx_at   ON banking_transactions(created_at DESC);


-- ============================================================
-- banking_cards
-- Registry of all issued Fiducia card IDs.
-- A card's data is written to a floppy disk as:  <accountKey>|<cardId>
-- The ATM terminal sends both values; we validate card_id exists,
-- account_key matches, and status = 'active'.
-- ============================================================
CREATE TABLE IF NOT EXISTS banking_cards (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,

  -- 'C' + 8 random decimal digits. Example: 'C47392841'.
  card_id     TEXT    NOT NULL UNIQUE,

  account_key TEXT    NOT NULL REFERENCES banking_accounts(key) ON DELETE CASCADE,

  status      TEXT    NOT NULL DEFAULT 'active'
              CHECK (status IN ('active', 'canceled')),
  -- Canceled cards remain for audit. Only 'active' cards pass auth checks.

  -- user_id (stringified) of the banker/admin who issued this card.
  issued_by   TEXT    NOT NULL DEFAULT '',

  created_at  TEXT    NOT NULL,
  updated_at  TEXT    NOT NULL
);

-- Active card count per account is checked against type-specific limits:
--   treasury  ≤ 1 active card
--   company   ≤ 2 active cards
--   personal  unlimited
CREATE INDEX IF NOT EXISTS idx_bk_cards_account ON banking_cards(account_key);
CREATE INDEX IF NOT EXISTS idx_bk_cards_status  ON banking_cards(status);


-- ============================================================
-- banking_shareholders
-- Per-company share ownership registry.
-- One row per (company, holder) pair; the shares column is updated
-- in-place via upsert (not append-only) for efficiency at this scale.
-- ============================================================
CREATE TABLE IF NOT EXISTS banking_shareholders (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  company_key TEXT    NOT NULL,
  holder_key  TEXT    NOT NULL,
  shares      INTEGER NOT NULL DEFAULT 0 CHECK (shares >= 0),
  created_at  TEXT    NOT NULL,
  updated_at  TEXT    NOT NULL,
  UNIQUE (company_key, holder_key)
);

CREATE INDEX IF NOT EXISTS idx_bk_sh_company ON banking_shareholders(company_key);
CREATE INDEX IF NOT EXISTS idx_bk_sh_holder  ON banking_shareholders(holder_key);


-- ============================================================
-- banking_value_history
-- 7-day rolling snapshots of company balance, used for the
-- sparkline chart on the company detail page and the 24h change %
-- on the top-companies leaderboard.
--
-- The Cron Trigger (daily at 03:00 UTC) inserts one row per live
-- company and prunes rows older than 7 days in the same batch.
-- ============================================================
CREATE TABLE IF NOT EXISTS banking_value_history (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  company_key TEXT    NOT NULL,
  value       REAL    NOT NULL,
  recorded_at TEXT    NOT NULL   -- ISO 8601 timestamp
);

CREATE INDEX IF NOT EXISTS idx_bk_val_company ON banking_value_history(company_key);
CREATE INDEX IF NOT EXISTS idx_bk_val_at      ON banking_value_history(recorded_at DESC);


-- ============================================================
-- banking_banker_assignments
-- Maps web users (role = 'banker') to exactly one treasury account.
-- Bankers can only see/act on accounts whose treasury_key matches
-- this assignment — mirroring the physical Admin Terminal's single-
-- Treasury binding stored in terminal_treasury.txt.
-- ============================================================
CREATE TABLE IF NOT EXISTS banking_banker_assignments (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,

  user_id      INTEGER NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
  -- ON DELETE CASCADE: if the web user is deleted, the assignment is gone.

  treasury_key TEXT    NOT NULL,
  -- Must reference a banking_accounts row with type = 'treasury'.
  -- No FK declared here because treasury deletion does not automatically
  -- revoke bankers (admin must handle that manually); the application
  -- layer validates treasury existence on every request.

  assigned_by  INTEGER REFERENCES users(id) ON DELETE SET NULL,
  -- user_id of the admin who created or last changed this assignment.

  assigned_at  TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bk_banker_user     ON banking_banker_assignments(user_id);
CREATE INDEX IF NOT EXISTS idx_bk_banker_treasury ON banking_banker_assignments(treasury_key);


-- ============================================================
-- banking_cc_tokens
-- Authentication tokens for ComputerCraft terminals using the HTTP
-- bridge (/api/banking/cc/*).
--
-- Each physical CC machine gets one token. An admin issues it via the
-- admin panel; the plaintext secret is displayed ONCE and must be
-- copied into cc_token.txt on the CC computer. This table stores only
-- the SHA-256 hex hash — the plaintext is never persisted server-side.
--
-- terminal_type controls which CC bridge endpoints the token may call:
--   atm            deposit, withdraw, validate-card, transfer, log
--   admin          all ATM routes + account management, card issuance,
--                  freeze/unfreeze, password reset, fine, issue-shares
--   app            balance read, transfer, log, change-password
--   clerk          (reserved; clerk currently talks locally via RedNet)
--   stock_exchange top-companies, shareholders, portfolio
-- ============================================================
CREATE TABLE IF NOT EXISTS banking_cc_tokens (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,

  -- SHA-256 hex digest of the plaintext secret stored on the CC computer.
  token_hash      TEXT    NOT NULL UNIQUE,

  terminal_type   TEXT    NOT NULL DEFAULT 'atm'
                  CHECK (terminal_type IN ('atm', 'admin', 'app', 'clerk', 'stock_exchange')),

  -- Human-readable label set by the admin, e.g. 'ATM — Main Hall'.
  computer_label  TEXT    NOT NULL DEFAULT '',

  -- Admin-type tokens: key of the Treasury this terminal is bound to.
  -- All admin-scope operations are automatically scoped to this treasury,
  -- matching the physical Admin Terminal's terminal_treasury.txt binding.
  -- All other token types: empty string.
  treasury_key    TEXT    NOT NULL DEFAULT '',

  created_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,

  -- Updated on every successful authenticated request.
  last_used_at    TEXT    NOT NULL DEFAULT '',

  -- Empty string = never expires. ISO timestamp for temporary tokens.
  expires_at      TEXT    NOT NULL DEFAULT '',

  created_at      TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bk_cc_hash ON banking_cc_tokens(token_hash);
CREATE INDEX IF NOT EXISTS idx_bk_cc_type ON banking_cc_tokens(terminal_type);
